# Generated by Django 5.0.2 on 2024-03-01 09:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
