# Generated by Django 5.0.2 on 2024-03-01 13:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blogs_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
