# Generated by Django 5.0.2 on 2024-03-01 14:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blogs_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tutorialpost',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
