# Generated by Django 5.0.2 on 2024-03-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blogs_content_alter_tutorialpost_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='meme',
            name='images',
            field=models.FileField(default=1, upload_to='memes'),
        ),
    ]
