# Generated by Django 5.0.2 on 2024-03-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_meme_images_delete_image_meme_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
